services:
  redis:
    image: redis:6.2-alpine
    command: ["redis-server", "--requirepass", "root@123456"]
    ports: ["6379:6379"]
    networks: [app-net]

  backend:
    build: ./Backend          
    ports: ["8080:8080"]
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: root@123456
    depends_on: [redis]       
    networks: [app-net]

  frontend:
    build: ./fitness-frontend 
    ports: ["80:80"]          
    depends_on: [backend]
    networks: [app-net]

networks:
  app-net:
    driver: bridge
